version: "3.6"

services:
  v2ray:
    image: guigeng/v2ray
    environment:
      - V2RAY_SERVER_IP=100.100.100.100
      - V2RAY_SERVER_PORT=10000
      - V2RAY_USERID=f56a8f9a-8002-4cfa-a6cf-7117eca6a5d8
    deploy: 
      replicas: 2
    networks:
      - proxy
      - bridge
      
  squid:
    image: guigeng/squid
    ports:
      - mode: host
        protocol: tcp
        published: 8080
        target: 3128
    volumes:
      - squidlog:/var/log/squid
      - squidconf:/etc/squid
    environment:
      - PEER_SERVER=v2ray
      - PEER_PORT=1080
    deploy:
      replicas: 2
    networks:
      - proxy
      - bridge
    depends_on:
      - v2ray
    
volumes:
  squidlog:
  squidconf:

networks:
  proxy:
  bridge:
    external: true
    name: bridge
